[Options]
makeflow_type = "lstbin_single_baseline" # this creates {basename} that look like "0_1"
source_script = "~/.bashrc"
base_mem = 15500
base_cpu = 1
timeout = "24h"
path_to_do_scripts = "/lustre/aoc/projects/hera/h6c-analysis/IDR3/src/hera_pipelines/pipelines/h6c/idr3/v1/lstbin/task_scripts"
toml_file = "/lustre/aoc/projects/hera/h6c-analysis/IDR3/src/hera_pipelines/pipelines/h6c/idr3/v1/lstbin/lststack_081_nights/single_bl_lst_stack.toml"  # this file
conda_env = "h6c_idr3" 
batch_system = "slurm"


[NOTEBOOK_OPTS]
nb_template_dir = '/lustre/aoc/projects/hera/h6c-analysis/IDR3/src/hera_notebook_templates/notebooks'
nb_output_repo = '/lustre/aoc/projects/hera/h6c-analysis/IDR3/notebooks'


[FILE_CFG] # this key is required
lst_branch_cut = 5.2 # in radians
where_inpainted_file_rules = [[".inpainted.uvh5", ".where_inpainted.h5"]]

[FILE_CFG.datafiles] # this key is required
datadir="/lustre/aoc/projects/hera/h6c-analysis/IDR3/"
nights=[
    "2459847",
    "2459848",
    "2459849",
    "2459853",
    "2459854",
    "2459855",
    # "2459856",
    "2459858",
    "2459859",
    "2459860",
    "2459861",
    "2459862",
    "2459863",
    "2459864",
    "2459866",
    "2459867",
    "2459868",
    "2459869",
    "2459870",
    "2459871",
    "2459872",
    "2459873",
    "2459874",
    "2459876",
    # "2459878",
    "2459879",
    "2459880",
    "2459881",
    "2459882",
    "2459883",
    "2459884",
    "2459887",
    "2459889",
    "2459890",
    "2459891",
    "2459893",
    "2459894",
    "2459898",
    "2459902",
    "2459903",
    "2459904",
    "2459905",
    "2459906",
    "2459907",
    "2459908",
    "2459909",
    "2459910",
    "2459912",
    "2459916",
    "2459917",
    "2459920",
    "2459922",
    "2459923",
    "2459930",
    "2459931",
    "2459933",
    "2459934",
    "2459935",
    "2459938",
    "2459939",
    "2459940",
    "2459941",
    "2459942",
    "2459943",
    "2459944",
    "2459945",
    "2459946",
    "2459947",
    "2459949",
    "2459950",
    "2459951",
    "2459952",
    "2459953",
    "2459954",
    "2459955",
    "2459957",
    "2459958",
    "2459960",
    "2459965",
    "2459966",
    "2459976",
]
fileglob = "{night}/single_baseline_files/zen.{night}.baseline.{baseline}.sum.smooth_calibrated.red_avg.inpainted.uvh5"


[LSTCAL_OPTS]
NBLS_FOR_LSTCAL=30
RUN_AMPLITUDE_CAL=true
RUN_TIP_TILT_PHASE_CAL=true
RUN_CROSS_POL_PHASE_CAL=true
INCLUDE_AUTOS=false # Include autos in calibration
FREQ_SMOOTHING_SCALE=30.0 # in MHz
TIME_SMOOTHING_SCALE=2500 # in seconds
BLACKLIST_TIMESCALE_FACTOR=10
BLACKLIST_RELATIVE_ERROR_THRESH=0.25
WHERE_INPAINTED_WGTS=1e-4
LSTCAL_FNAME_FORMAT = "single_bl_reinpaint_1000ns/zen.{night}.lstcal.hdf5"

[LST_STACK_OPTS] # this precise key is used by single_bl_lststack.ipynb, variables are case-sensitive
OUTDIR = "/lustre/aoc/projects/hera/h6c-analysis/IDR3/lststack-outputs-081-nights"
FNAME_FORMAT = "single_bl_reinpaint_1000ns/zen.LST.baseline.{bl_str}.sum.uvh5"
USE_LSTCAL_GAINS = true # this will be ignored if the PRELIMINARY flag is true
FM_LOW_FREQ=87.5 # in MHz
FM_HIGH_FREQ=108.0 # in MHz
EIGENVAL_CUTOFF=1e-12
INPAINT_DELAY=1000 # in ns
AUTO_INPAINT_DELAY=100 # in ns
REINPAINT_AUTOS=false
INPAINT_WIDTH_FACTOR=0.5
INPAINT_ZERO_DIST_WEIGHT=1e-2
MIN_NIGHTS_PER_BIN=3
MAX_CHANNEL_NIGHTLY_FLAG_FRAC=0.25
MOD_Z_TO_REINPAINT=5 # TODO: revisit
AUTO_FR_SPECTRUM_FILE="/lustre/aoc/projects/hera/zmartino/hera_frf/spectra_cache/spectra_cache_hera_auto.h5"
GAUSS_FIT_BUFFER_CUT=1e-5
CG_TOL=1e-6
CG_ITER_LIM=500
FR0_FILTER=true
FR0_HALFWIDTH=0.01 # in mHz
FR0_FILT_AUTOS=false

############################################################################################################

[WorkFlow]
actions = ["PRELIMINARY_SINGLE_BASELINE_LSTSTACK",
           "SINGLE_NIGHT_LSTCAL",
           "SINGLE_BASELINE_LSTSTACK"]

[PRELIMINARY_SINGLE_BASELINE_LSTSTACK]
mem = 80000
args = ["{basename}", 
        "${Options:toml_file}",
       ]

[SINGLE_NIGHT_LSTCAL]
prereqs = "PRELIMINARY_SINGLE_BASELINE_LSTSTACK"
prereq_chunk_size = "all"
mem = 80000
args = ["{basename}", 
        "${Options:toml_file}",
       ]

[SINGLE_BASELINE_LSTSTACK]
prereqs = "SINGLE_NIGHT_LSTCAL"
prereq_chunk_size = "all"
mem = 80000
args = ["{basename}", 
        "${Options:toml_file}",
       ]
